### ISSUE TITLE
build: integrate apicompat into CI pipeline

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#368]
[`apicompat`](https://github.com/bradleyfalzon/apicompat) is a tool which checks for breaking changes across exported API's of a Go package. The tool does so by checking recent commits together with a set of rules.

The project states it is under "heavy development" and might change still, so let's try one repository first and see how it goes.

**Comment by adamdecaf** [comment]
There's also `apidiff` from the Go team:  (super experimental as-of today)

```
$ go get golang.org/x/exp/cmd/apidiff 

$ apidiff 
usage:
apidiff OLD NEW
   compares OLD and NEW package APIs
   where OLD and NEW are either import paths or files of export data
apidiff -w FILE IMPORT_PATH
   writes export data of the package at IMPORT_PATH to FILE
  -incompatible
    	display only incompatible changes
  -w string
    	file for export data
panic: runtime error: index out of range

goroutine 1 [running]:
main.loadPackage(0x0, 0x0, 0x14b0328, 0x1311a60, 0x14b0328)
	/Users/adam/code/src/golang.org/x/exp/cmd/apidiff/main.go:89 +0x1cd
main.mustLoadPackage(0x0, 0x0, 0x0)
	/Users/adam/code/src/golang.org/x/exp/cmd/apidiff/main.go:76 +0x3f
main.mustLoadOrRead(0x0, 0x0, 0xc0000123f8)
	/Users/adam/code/src/golang.org/x/exp/cmd/apidiff/main.go:71 +0x72
main.main()
	/Users/adam/code/src/golang.org/x/exp/cmd/apidiff/main.go:46 +0x184
```

**Comment by bkmoovio** [comment]
Do we want to wait on both of these, until they are a bit more mature?

**Comment by adamdecaf** [comment]
Yeah. This isn't a priority.
