### ISSUE TITLE
Adding batch to file, can't get content back

### ISSUE THREAD

**Issue by tipputhynhean** [moov-io/ach#786]
- Create a new file with
```
curl --request POST \
  --url http://localhost:8080/files/create \
  --header 'content-type: application/json' \
  --cookie 'adminer_sid=7a6e047af20fd05104d01c400d1d8eb2; adminer_key=625e1ceddcb2167ffb796798afc73f39; adminer_sid=d75d30ced834a1da6b2587520dde9dfd; adminer_key=0276dc1548007891e5d61b970bdb6678' \
  --data '{
	"fileHeader": {
		"id": "",
		"immediateDestination": "121042882",
		"immediateOrigin": "121042882",
		"fileCreationDate": "200217",
		"fileCreationTime": "0437",
		"fileIDModifier": "1",
		"immediateDestinationName": "Moov Bank",
		"immediateOriginName": "Moov Bank"
	},
	"batches": [
		{
			"batchHeader": {
				"id": "",
				"serviceClassCode": 200,
				"companyName": "Friendly Corp",
				"companyIdentification": "123456789",
				"standardEntryClassCode": "PPD",
				"companyEntryDescription": "apitest tr",
				"companyDescriptiveDate": "200217",
				"effectiveEntryDate": "200218",
				"originatorStatusCode": 1,
				"ODFIIdentification": "12104288",
				"batchNumber": 1
			},
			"entryDetails": [
				{
					"id": "",
					"transactionCode": 37,
					"RDFIIdentification": "12104288",
					"checkDigit": "2",
					"DFIAccountNumber": "000000099",
					"amount": 2500,
					"identificationNumber": "7813fde9df675a0",
					"individualName": "Wrong debit",
					"discretionaryData": "ap",
					"addendaRecordIndicator": 1,
					"traceNumber": "121042887841793"
				}
			]
		}
	]
}'
```
Then get the content of it back
```
curl --request GET \
  --url http://localhost:8080/files/65b0d892fb6227e9a331a464b10f1ac134a53fec/contents \
  --cookie 'adminer_sid=d75d30ced834a1da6b2587520dde9dfd; adminer_key=0276dc1548007891e5d61b970bdb6678'
```
You will see the plain text ach file in the response.

- Now add a new batch to the file
```
curl --request POST \
  --url http://localhost:8080/files/65b0d892fb6227e9a331a464b10f1ac134a53fec/batches \
  --header 'content-type: application/json' \
  --cookie 'adminer_sid=d75d30ced834a1da6b2587520dde9dfd; adminer_key=0276dc1548007891e5d61b970bdb6678' \
  --data '{
  "batchHeader": {
    "serviceClassCode": 220,
    "companyName": "Acme Corp",
    "companyIdentification": "1",
    "ODFIIdentification": "12345678"
  },
  "entryDetails": [
    {
      "transactionCode": 22,
      "RDFIIdentification": "12345678",
      "checkDigit": "0",
      "DFIAccountNumber": "181141847",
      "amount": 1235,
      "individualName": "Taylor Swift"
    }
  ]
}'
```

Then get the content of the file again
```
curl --request GET \
  --url http://localhost:8080/files/65b0d892fb6227e9a331a464b10f1ac134a53fec/contents \
  --cookie 'adminer_sid=d75d30ced834a1da6b2587520dde9dfd; adminer_key=0276dc1548007891e5d61b970bdb6678'
```

The response is empty

- Try flatten the file with 
```
curl --request POST \
  --url http://localhost:8080/files/65b0d892fb6227e9a331a464b10f1ac134a53fec/flatten \
  --cookie 'adminer_sid=d75d30ced834a1da6b2587520dde9dfd; adminer_key=0276dc1548007891e5d61b970bdb6678'
```
The response is error 
![image](https://user-images.githubusercontent.com/20786858/96330734-d678d200-1081-11eb-9ded-e53c91e1b84d.png)

- Full log on docker container:
```
ts=2020-10-17T06:30:29.1467643Z caller=main.go:65 startup="Starting ach server version v1.5.0-rc1"
ts=2020-10-17T06:30:29.1476125Z caller=main.go:144 startup="binding to :8080 for HTTP server"
ts=2020-10-17T06:30:29.1476526Z caller=main.go:126 admin="listening on [::]:9090"
ts=2020-10-17T06:56:39.0800835Z caller=files.go:86 component=HTTP files=createFile requestID= error=null
ts=2020-10-17T06:57:00.4684768Z caller=files.go:271 component=HTTP files=getFileContents requestID= error=null
ts=2020-10-17T07:00:15.6151922Z caller=batches.go:61 component=HTTP batches=createBatch file=65b0d892fb6227e9a331a464b10f1ac134a53fec requestID= error=null
ts=2020-10-17T07:00:51.5071743Z caller=files.go:271 component=HTTP files=getFileContents requestID= error="problem writing plaintext file 65b0d892fb6227e9a331a464b10f1ac134a53fec: use an implementation of batch or NewBatch"
2020/10/17 07:03:41 http: panic serving 172.22.0.1:50914: runtime error: invalid memory address or nil pointer dereference
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc0000c17c0)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x9cd780, 0xe46580)
	/usr/local/go/src/runtime/panic.go:975 +0x3e9
github.com/moov-io/ach.(*File).AddBatch(0xc0000ac900, 0x0, 0x0, 0xb15080, 0xc000097180, 0x1)
	/go/src/github.com/moov-io/ach/file.go:465 +0x26
github.com/moov-io/ach.(*File).FlattenBatches(0xc000304d80, 0x0, 0x0, 0xc000304d80)
	/go/src/github.com/moov-io/ach/file.go:1053 +0x3f6
github.com/moov-io/ach/server.(*service).FlattenBatches(0xc0002160e0, 0xc0000980ac, 0x28, 0x40b07f, 0x9ee860, 0xc000097120)
	/go/src/github.com/moov-io/ach/server/service.go:239 +0xa5
github.com/moov-io/ach/server.flattenBatchesEndpoint.func1(0xb1e960, 0xc0000a14a0, 0x9ee860, 0xc000097120, 0xc000097120, 0x0, 0x0, 0x120)
	/go/src/github.com/moov-io/ach/server/files.go:485 +0xa8
github.com/go-kit/kit/transport/http.Server.ServeHTTP(0xc000234780, 0xa90b68, 0xa90bb0, 0xc00022c248, 0x1, 0x1, 0xc00022c250, 0x1, 0x1, 0xa90ba8, ...)
	/go/pkg/mod/github.com/go-kit/kit@v0.10.0/transport/http/server.go:121 +0x344
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000244000, 0xb1d320, 0xc00032e1c0, 0xc0000e6600)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc00024c0e0, 0xb1d320, 0xc00032e1c0, 0xc0000e6600)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0000c17c0, 0xb1e8a0, 0xc0000c2980)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
```

Ran on docker image `moov/ach:latest`

**Comment by adamdecaf** [comment]
This is a bug - I've got a patch working and will open a PR here that fixes the underlying issue. 

Your batch creation request is missing a few fields. Here's my working example

```
curl --request POST -v \
--url http://localhost:8080/files/c7ec366d05e277b2ca80bd447408e46e791dd852/batches \
--header 'content-type: application/json' \
--data '{
    "entryDetails": [
        {
            "individualName": "Taylor Swift",
            "amount": 1235,
            "DFIAccountNumber": "181141847",
            "checkDigit": "0",
            "RDFIIdentification": "12345678",
            "transactionCode": 22
        }
    ],
    "batchHeader": {
        "ODFIIdentification": "12345678",
        "companyIdentification": "1",
        "companyName": "Acme Corp",
        "serviceClassCode": 220,
        "standardEntryClassCode": "PPD",
        "companyEntryDescription": "test"
   }
}'
```

**Comment by tipputhynhean** [comment]
I was testing your PR, it seem there's still some issue. Manually insert `traceNumber` won't work, it will stay the same at `123456780000001`.  even after inserting multiple time it still stay at that number

**Comment by adamdecaf** [comment]
By default I'm pretty sure we overwrite those to be in sequential ordering. If you need custom trace number that's supported as part of a File's `ValidateOpts` struct. Can you try that? 

See: https://github.com/moov-io/ach/blob/v1.5.0-rc1/file.go#L556-L557

**Comment by tipputhynhean** [comment]
This is the behavior I have observed, 
- if you have multiple entries inside `entryDetails` when adding batch to file with `localhost:8080/files/fileID/batches`, the `traceNumber` will be correctly in order. Ex:
```
{
	"batchHeader": {
		"id": "7d4008a5bd94214f9cd75dc8b05e2103f70780a3",
		"serviceClassCode": 220,
		"companyName": "ABA Bank",
		"companyIdentification": "1210428821",
		"standardEntryClassCode": "PPD",
		"companyEntryDescription": "ACH Transfer",
		"ODFIIdentification": "121042882"
	},
	"entryDetails": [
		{
			"transactionCode": 32,
			"RDFIIdentification": "06200001",
			"checkDigit": "9",
			"DFIAccountNumber": "12104288",
			"amount": 1400,
			"individualName": "Test",
			"identificationNumber": "1603090389308wo"
		},
		{
			"transactionCode": 32,
			"RDFIIdentification": "06200001",
			"checkDigit": "9",
			"DFIAccountNumber": "12104288",
			"amount": 1400,
			"individualName": "Test",
			"identificationNumber": "1603090389308wo"
		}
	]
}
```
- when you add a batch with the same `batchHeader` as a batch that already exist in the file, it doesn't add entries to that batch, it will create a new batch in the `batches` array. I'm not sure if this is intended behavior.
- If you have two batches with the same `batchHeader` , and you try to call flatten `localhost:8080/files/fileID/flatten`, it will show 
```
{
  "error": "batch #1 (PPD) TraceNumber must be in ascending order, 121042880000001 is less than or equal to last number 121042880000001"
}
```
modify something in the `batchHeader` will allow flatten to success

**Comment by adamdecaf** [comment]
When adding a batch we don't call Validate. This is to allow adding multiple batches into a file until it's ready to go and why we have validate as a separate endpoint.

This does expose a bad user experience because flatten expects the `File.Create()` has been called, which isn't done until the validate/contents routes are called. 

Trace numbers are re-written as part of Create, so calling flatten when the file isn't built would have an error.

I think we should call Create() prior to flatten, as that endpoint expects it to be fully built/created anyway.

**Comment by adamdecaf** [comment]
> "flatten expects the File.Create() has been called, which isn't done until the validate/contents routes are called."

This is incorrect. We call [`Create()` prior to flattening](https://github.com/moov-io/ach/blob/v1.5.0-rc1/server/service.go#L236) already, so this seems to be an issue where [creating the file with `ValidateOpts`](https://github.com/moov-io/ach/issues/793) would allow us to disable the Origin check.

cc @vxio as he's working on supporting that.
